title: Ryan Cali # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Engineer with 9 years of experience working in the healthcare sector on cloud and AI applications integrated with ETL pipelines.
  <br><br>
  Previous experience working in computer vision and deep learning research in disease at Harvard Medical School and Massachusetts General Hospital.
  <br><br>
  <a href="https://www.linkedin.com/in/ryan-cali-64201417a/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 


sass:
  style: compressed